language: c
sudo: false
arch:
  - amd64
  - ppc64le
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
env:
 global:
   - PACKAGE="ppx_tools"
   - PRE_INSTALL_HOOK="cd /home/opam/opam-repository && git pull origin master && opam update -u -y"
 matrix:
   - DISTRO=ubuntu-lts OCAML_VERSION=4.11.0+trunk OCAML_BETA=enable
   - DISTRO=ubuntu-lts OCAML_VERSION=4.10.0
   - DISTRO=ubuntu-lts OCAML_VERSION=4.09.1
   - DISTRO=ubuntu-lts OCAML_VERSION=4.08.1
  exclude:
   - arch: ppc64le
     env: DISTRO=ubuntu-lts OCAML_VERSION=4.11.0+trunk OCAML_BETA=enable
